// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

// SwaggerInfo holds the Swagger spec
var SwaggerInfo = &swag.Spec{
	Version:     "1.0.0",
	Host:        "localhost:8080",  // Replace with your actual host
	BasePath:    "/api",            // Replace with your actual base path
	Schemes:     []string{"http"}, // You can add "https" if applicable
	Title:       "E-Commerce API",
	Description: "API documentation for the E-commerce platform",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  `{
		"swagger": "2.0",
		"info": {
			"description": "API documentation for the E-commerce platform",
			"title": "E-Commerce API",
			"version": "1.0.0",
			"contact": {
				"name": "Joshua",
				"email": "jimijay.oj@gmail.com"
			}
		},
		"host": "localhost:8080",
		"basePath": "/api",
		"schemes": ["http"],
		"paths": {},
		"definitions": {}
	}`,
	LeftDelim:  "{{",
	RightDelim: "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
